export const articles = {
  'hospital-website-creation-problems-and-success-steps': {
    title: 'Hospital Website Creation: Common Problems, Practical Steps, and the Road to Success',
    description: 'Learn how to create a successful hospital website by solving patient trust, accessibility, content, privacy, mobile, local SEO, and enquiry challenges.',
    published: '2026-09-25',
    readingTime: '10 min read',
    intro: 'A hospital website has a higher responsibility than a standard business website. Patients and families may be anxious, short on time, using a phone, or looking for urgent information. Success comes from making the right information trustworthy, accessible, and actionable at every stage of the patient journey.',
    sections: [
      ['Understand the problems before designing pages', ['Hospital website projects often begin with too much information and no clear ownership. Departments request separate pages, medical teams use different terminology, and important details such as doctor availability, services, phone numbers, and visiting hours become inconsistent.', 'Patients also arrive with different needs. Someone may need emergency guidance, another person may want to book an appointment, and a family member may be comparing departments or looking for insurance information. Treating every visitor the same creates a confusing navigation system.', 'Start by listing the most important patient questions and the business outcomes the website must support: find the right department, choose a doctor, request an appointment, understand a service, reach the hospital, or contact the right team.']],
      ['Create one trusted source for hospital information', ['Outdated information damages confidence quickly. A doctor profile with an old schedule, a missing phone number, or conflicting visiting hours can make the entire hospital appear unreliable. Assign an owner for each content area and define how changes are reviewed and approved.', 'Create a content inventory covering departments, treatments, doctors, facilities, emergency information, appointment routes, insurance and payment guidance, patient resources, contact details, and location pages. Include a review date for information that can change.', 'Use plain language first and explain medical terms when they are necessary. Every page should answer what the service is, who it is for, what the patient should do next, and how to get help with questions.']],
      ['Design clear patient journeys', ['Do not make patients search through a large menu to find a basic action. Put high-priority tasks such as Book an appointment, Find a doctor, View departments, Get directions, Call the hospital, and Emergency information where they are easy to reach on every device.', 'Design the complete journey, not only the landing page. A booking journey needs service selection, doctor or location choice, available times, patient details, confirmation, cancellation guidance, and a reliable follow-up process. If the website cannot complete a step online, explain exactly what the patient should do instead.', 'Test the journeys with people who were not involved in the project. Watch where they hesitate, misunderstand a label, or choose the wrong department. Their questions are better evidence than assumptions made in an internal meeting.']],
      ['Build for trust, privacy, and accessibility', ['Healthcare content requires careful review. Show medical qualifications, department information, affiliations, contact methods, and clear disclaimers without making unsupported claims. Avoid promising outcomes or using sensational language that can mislead vulnerable visitors.', 'Protect appointment and enquiry data with secure forms, limited access, appropriate retention, and a clear privacy notice. Review every third-party service, analytics tool, chat widget, and integration before sending personal information to it.', 'Meet accessibility expectations with readable contrast, keyboard navigation, descriptive labels, captions or transcripts where needed, meaningful headings, large tap targets, and content that works with assistive technology. Accessibility is essential for patients, carers, older visitors, and people using a phone in difficult conditions.']],
      ['Make the website useful on mobile and in local search', ['Many patients search for a hospital, department, doctor, phone number, or directions from a mobile device. Keep important content fast to load, make phone and map actions obvious, and test on smaller screens and slower connections.', 'Create accurate location and service pages with consistent name, address, phone number, opening hours, parking details, transport guidance, and department-specific contact information. Use descriptive page titles and structured data where appropriate, but keep the information useful to people rather than writing for search engines alone.', 'Check that the hospital appears correctly in its business listings and that local search visitors land on the page that answers their question. A page about cardiology should help a patient understand cardiology services and the next step, not send everyone back to a generic homepage.']],
      ['Connect the website to the hospital operation', ['A website cannot succeed if online requests disappear into an inbox. Connect appointment requests, contact forms, doctor data, locations, and relevant patient services to the systems and teams that can act on them. Define what happens when an integration fails and who monitors it.', 'Use clear ownership and response targets for every enquiry route. Test confirmation messages, duplicate submissions, failed payments, unavailable appointment times, cancelled requests, and changes to doctor or department data before launch.', 'Keep clinical systems and public website functions appropriately separated. The website should make access to care easier without exposing information that should remain inside controlled hospital systems.']],
      ['Measure success and improve after launch', ['A successful hospital website is measured by patient outcomes and operational reliability, not only visitor numbers. Track completed appointment requests, calls from service pages, doctor searches, directions requests, form completion, search queries, accessibility issues, and unanswered enquiries.', 'Set a baseline before launch and review results by device, location, service, and journey. A rise in visits with no improvement in completed actions may indicate a content or workflow problem. A fall in support calls can be positive when patients are finding accurate answers, but it should be checked against patient satisfaction and safety requirements.', 'Run a monthly content and technical review, then use real questions from patients, reception teams, and clinicians to prioritize improvements. Hospital website creation is successful when the site remains accurate, respectful, secure, and genuinely easier to use over time.']]
    ],
    faqs: [['What should a hospital website include?', 'A hospital website should make departments, doctors, treatments, appointment options, emergency guidance, visiting information, locations, contact details, accessibility support, and patient resources easy to find.'], ['How long does hospital website development take?', 'A hospital website timeline depends on the number of departments, content approval process, appointment integrations, accessibility requirements, and migration work. A phased launch can deliver priority patient journeys while the remaining content is reviewed.'], ['How do you measure a successful hospital website?', 'Measure completed appointment requests, calls from service pages, doctor and department searches, directions requests, form completion, unanswered enquiries, accessibility issues, and the accuracy of critical information.']],
    serviceLink: { href: '/web-development', label: 'Explore website development' }
  },
  'website-maintenance-checklist-for-small-businesses': {
    title: 'The Website Maintenance Checklist for Small Businesses',
    description: 'A practical website maintenance checklist covering security, backups, forms, performance, content, analytics, and ownership for small businesses.',
    published: '2026-09-25',
    readingTime: '8 min read',
    intro: 'A small business website is part of your operations, not a one-time brochure. A lightweight maintenance routine keeps it trustworthy for customers and less likely to become an expensive emergency.',
    sections: [
      ['Start with ownership and access', ['Keep a simple record of who owns the domain, hosting account, website platform, analytics, email forms, payment services, and third-party integrations. Store recovery details securely and review access when someone leaves the business.', 'Assign one person to notice issues and one person who can approve changes. Maintenance becomes unreliable when everyone assumes somebody else is watching the website.']],
      ['Check security and software updates', ['Review the content management system, frameworks, plugins, themes, libraries, server packages, and certificates on a regular schedule. Apply security updates promptly, but test important changes before they reach the live site.', 'Remove unused accounts, integrations, and extensions. Use strong individual logins and multi-factor authentication wherever it is available. A smaller, current system is easier to protect than a crowded one nobody understands.']],
      ['Test the journeys that create business', ['Submit every important form and confirm that the customer and internal notifications arrive. Test phone links, email links, booking flows, logins, checkout, downloads, and any enquiry routing that matters to the business.', 'Run these checks from a phone as well as a desktop browser. A form that looks fine but silently fails, sends messages to an abandoned inbox, or requires an unusable CAPTCHA can turn paid traffic into lost opportunities.']],
      ['Protect data and prove recovery', ['Maintain automated backups for the website, database, uploaded files, and relevant configuration. Keep more than one recent recovery point, and avoid storing the only copy on the same server as the live website.', 'A backup is only useful if it can be restored. Test a restoration periodically and record how long it takes, what is included, and who can make the site available again.']],
      ['Measure performance and findability', ['Review load speed, uptime, broken links, mobile layout, image sizes, and the experience of the most visited pages. Look for pages that have become slow because of oversized media, unnecessary scripts, or accumulated extensions.', 'Check search indexing, page titles, descriptions, structured data, redirects, and analytics tracking after major changes. A monthly review should answer which pages attract the right visitors and whether those visitors can take the next step.']],
      ['Keep content and the next action current', ['Check opening hours, contact details, services, pricing signals, team information, legal pages, case studies, and downloadable documents. Remove expired announcements and replace outdated screenshots or claims.', 'End each review with a short action list: urgent fixes, useful improvements, and items to monitor. For a small business, a dependable maintenance plan is often more valuable than an occasional redesign because it keeps small problems from becoming customer-facing failures.']]
    ],
    faqs: [['What is included in website maintenance?', 'Website maintenance can include security and software updates, backups, uptime checks, broken-link checks, form testing, performance reviews, content changes, analytics checks, and technical SEO monitoring.'], ['How often should a business website be maintained?', 'Review critical forms, uptime, backups, and security regularly. A monthly review is a useful baseline for content, performance, indexing, redirects, and analytics, with urgent security updates handled sooner.'], ['Is website maintenance better than redesigning a website?', 'Maintenance keeps a working website secure, accurate, and useful. A redesign is appropriate when the structure, user journeys, technology, or visual system no longer supports the business. The right choice depends on evidence rather than age alone.']],
    serviceLink: { href: '/services', label: 'Explore website maintenance services' }
  },
  'why-business-website-contact-forms-lose-leads': {
    title: 'Why Business Website Contact Forms Lose Leads',
    description: 'Find and fix the most common reasons business website contact forms lose enquiries, from unclear fields and broken notifications to slow follow-up.',
    published: '2026-09-25',
    readingTime: '7 min read',
    intro: 'A contact form can look perfectly normal while quietly losing potential customers. The useful question is not whether a form exists, but whether a real person can complete it, whether the enquiry arrives, and whether the business responds in time.',
    sections: [
      ['Ask only for the information needed next', ['Every extra field adds effort before the visitor has received any value. Start with the information a team genuinely needs to respond, such as name, contact method, service interest, and a short description of the request.', 'If a longer discovery process is necessary, split it into stages or make optional questions clearly optional. Explain why sensitive or unusual information is being requested.']],
      ['Make the action and status obvious', ['Use a specific action label such as Request a quote or Discuss my project rather than a vague Submit. Tell the visitor what happens after sending the form and when they should expect a response.', 'A successful submission should produce a clear confirmation on the page and a confirmation message when appropriate. Preserve entered values when validation fails so the visitor does not have to start again.']],
      ['Treat notifications as a production system', ['Send test enquiries from different devices and verify delivery to every internal recipient. Check spam folders, reply-to addresses, routing rules, autoresponders, and the mailbox used by the team that handles enquiries.', 'Do not rely on a single email notification as the only record. Where the workflow matters, store the enquiry securely in a CRM, dashboard, or other controlled system with an owner and timestamp.']],
      ['Design for phones and real network conditions', ['Most service enquiries happen on mobile devices. Use large tap targets, appropriate input types, short labels, and a layout that does not require sideways scrolling or precise tapping.', 'Test on a slower connection and with keyboard navigation. Keep the form usable when scripts are delayed, a browser autofills a field unexpectedly, or a visitor needs to correct one invalid value.']],
      ['Measure the complete enquiry journey', ['Track form views, starts, validation errors, successful submissions, duplicate submissions, and completed follow-up. Compare these events with phone calls, chat conversations, and enquiries that arrive through other channels.', 'A high number of submissions does not prove the form is working well if the enquiries are poor quality or never receive a response. Review the journey with the sales or support team and improve the points where real prospects get stuck.']]
    ]
  },
  'ecommerce-order-flow-checklist-for-growing-retailers': {
    title: 'The E-commerce Order Flow Checklist for Growing Retailers',
    description: 'A practical e-commerce order flow checklist covering product data, checkout, payments, fulfilment, customer updates, returns, and operational monitoring.',
    published: '2026-09-25',
    readingTime: '9 min read',
    intro: 'An online store is a chain of connected promises: the product is available, the price is correct, payment is secure, the order is recorded, and the customer knows what happens next. Testing the entire chain exposes problems that a polished storefront can hide.',
    sections: [
      ['Make product information decision-ready', ['Review names, descriptions, variants, images, dimensions, availability, delivery expectations, tax treatment, and return information. Customers should be able to decide without contacting the business for basic facts.', 'Keep product and inventory data consistent across the storefront, admin tools, marketplaces, and fulfilment systems. A stock count that is correct in one place and stale in another creates avoidable cancellations.']],
      ['Test the cart and checkout states', ['Run the journey with one item, multiple items, a variant, a discount, an unavailable item, and an address that requires different delivery rules. Confirm that totals, taxes, shipping, and minimum-order rules remain correct at every step.', 'Test validation, refreshes, back navigation, abandoned carts, duplicate clicks, expired sessions, and failed payment attempts. Customers need a clear way to recover without accidentally creating two orders.']],
      ['Verify payment and order records', ['Use the payment provider test environment to confirm successful payments, declines, cancellations, refunds, delayed confirmations, and webhook retries. The store should not mark an order as paid based only on a browser redirect.', 'Check that every successful order receives one reliable internal record with payment status, customer details, line items, fulfilment state, and an audit trail. Reconcile orders against the payment provider regularly.']],
      ['Connect fulfilment to customer communication', ['Define what happens after payment: who picks the order, how stock is reserved, when the parcel is handed over, and which events trigger customer messages. Use clear statuses that staff and customers can understand.', 'Send useful updates for confirmation, dispatch, delivery issues, cancellations, and refunds. Make support contact details easy to find when an order does not follow the expected path.']],
      ['Measure profit and service quality', ['Monitor checkout completion, payment failure rate, average order value, delivery time, refund rate, support contacts, and repeat purchase. Break results down by device, product, campaign, and delivery region when the data supports it.', 'Review the most common failed or cancelled orders with the operations team. Small improvements to delivery clarity, product data, or payment recovery can be more valuable than adding another storefront feature.']]
    ]
  },
  'when-a-custom-business-dashboard-is-worth-building': {
    title: 'When Is a Custom Business Dashboard Worth Building?',
    description: 'Decide whether a custom business dashboard is worthwhile by mapping repeated decisions, data sources, permissions, workflow gaps, and measurable operational value.',
    published: '2026-09-25',
    readingTime: '8 min read',
    intro: 'A dashboard is worthwhile when it helps people make important decisions with less delay and less manual reconciliation. It is not worthwhile merely because a business has several spreadsheets or because a chart looks impressive in a demo.',
    sections: [
      ['Start with repeated decisions', ['List the decisions teams make every day or week: which jobs need attention, which customers need a response, which orders are delayed, which stock needs replenishment, or which service is underperforming.', 'Describe the current path from question to decision. Count the files, systems, manual checks, handoffs, and delays involved. This shows whether the problem is visibility, workflow, data quality, or unclear ownership.']],
      ['Find the smallest useful view', ['A first dashboard should answer a small number of high-value questions for a defined role. An operations lead may need overdue work and capacity; a sales lead may need qualified enquiries and next actions; a director may need trends and exceptions.', 'Avoid combining every metric into one screen. Separate daily action views from periodic reporting, and give each metric a definition, source, owner, and update expectation.']],
      ['Map the data before designing charts', ['Identify where each data point lives, who can access it, how often it changes, and how reliable it is. Check identifiers, duplicate records, missing values, time zones, status definitions, and historical changes before promising real-time reporting.', 'A clear limitation is better than a precise-looking number built from inconsistent sources. Resolve important data ownership questions during discovery rather than hiding them behind visual design.']],
      ['Build permissions and workflows in from the start', ['Dashboards often expose customer, financial, or employee information. Define roles, row-level access, audit history, retention, and secure authentication before connecting production data.', 'If the dashboard is meant to improve operations, include the next action where appropriate: assign an owner, update a status, add a note, approve a request, or open the underlying record. Reporting without a path to action can add another place for work to become stale.']],
      ['Set a measurable return threshold', ['Choose measures that connect the dashboard to operating value: fewer hours spent reconciling, faster response times, fewer missed tasks, shorter order cycles, better forecast accuracy, or lower support volume.', 'Start with a dependable release and review usage after launch. Remove unused views, improve confusing definitions, and add automation only after the core workflow is trusted. A small dashboard that changes behavior is more valuable than a large dashboard that nobody opens.']]
    ]
  },
  'planning-a-web-development-brief': {
    title: 'Website Development Brief: Template and Requirements Checklist',
    description: 'Use this website development brief template to define project requirements, audiences, content, integrations, budget, SEO, accessibility, testing, and launch ownership.',
    published: '2026-09-23',
    readingTime: '7 min read',
    intro: 'A website development brief is the working document that turns a business goal into clear website project requirements. This practical web development project brief template helps teams define scope, audience, content, integrations, budget, SEO, accessibility, testing, and launch ownership before development begins.',
    sections: [
      ['Start with the business outcome', ['Explain why the website project exists before listing pages or features. Useful outcomes include increasing qualified enquiries, reducing support requests, improving recruitment, enabling self-service, or replacing a system that is difficult to maintain.', 'Add a small set of measurable indicators to the website requirements document. These might include completed enquiries, successful purchases, task-completion rate, organic landing-page traffic, publishing time, or support-ticket volume.']],
      ['Describe the audience and their decisions', ['Identify the primary audiences, what they already know, what questions they need answered, and what action they should be able to complete. Include important accessibility, language, device, and location considerations.', 'Real customer questions are more useful than vague personas. Sales calls, support messages, internal search terms, and analytics can reveal the language and concerns the website needs to address.']],
      ['Inventory content, functionality, and integrations', ['List existing content that can be retained, material that needs revision, and new content that must be created. Assign an owner and approval path because late content is a common cause of delayed launches.', 'Describe functional needs as user journeys: request a quote, find a service, purchase a product, book a time, or manage an account. Document integrations such as payments, CRM, email marketing, analytics, authentication, inventory, and internal APIs.']],
      ['Make constraints visible', ['State the target launch window, available budget range, legal or compliance requirements, hosting constraints, internal technologies, and people responsible for decisions. Constraints help the team recommend an appropriate scope instead of an idealized one.', 'Separate requirements that are essential for launch from useful later improvements. This protects the central outcome when new ideas appear during delivery.']],
      ['Define launch and ownership', ['A website needs an owner after release. Agree who will publish content, review analytics, manage software updates, monitor forms and uptime, respond to security issues, and prioritize improvements.', 'Ask prospective partners to explain discovery, accessibility, performance, technical SEO, testing, migration, analytics, deployment, training, documentation, and post-launch support. Their answers are more useful than a list of technologies alone.']]
    ],
    faqs: [['What is a website development brief?', 'A website development brief is a working document that explains the business outcome, audience, content, functionality, integrations, constraints, budget, success measures, and ownership needed to plan a website project.'], ['What should a website requirements document include?', 'Include user journeys, content and page requirements, accessibility, SEO, integrations, permissions, performance expectations, analytics, legal needs, launch criteria, timeline, and the people responsible for decisions.'], ['Why use a website development brief template?', 'A template gives stakeholders a shared structure for discussing website project requirements. It reduces missed dependencies, makes estimates more realistic, and helps a development team protect the outcome when new ideas appear.']],
    serviceLink: { href: '/web-development', label: 'Explore website development' }
  },
  'choosing-an-mvp-scope': {
    title: 'Choosing an MVP Scope That Produces Useful Evidence',
    description: 'Learn how to define an MVP around one valuable outcome, prioritize assumptions, control technical risk, and plan measurable product learning.',
    published: '2026-09-23',
    readingTime: '8 min read',
    intro: 'A minimum viable product is not the smallest collection of features a team can ship. It is the smallest dependable product that tests the most important assumption and delivers a recognizable outcome for a specific user.',
    sections: [
      ['Name the promise and the riskiest assumption', ['Write one sentence describing who the product helps, the problem it addresses, and the result it enables. If the sentence contains several audiences or outcomes, the first release may already be too broad.', 'Then list what must be true for the product to work: users experience the problem, the proposed workflow is acceptable, required data is available, integrations are feasible, and the operating model is sustainable. Test the assumption that could invalidate the project first.']],
      ['Map one complete journey', ['Choose the central journey from entry to completed outcome. Include necessary states such as validation, confirmation, failure, cancellation, permissions, and recovery—not only the happy path.', 'Supporting features belong in the MVP only when the central journey cannot be trusted or operated without them. This distinction prevents dashboards, preferences, and secondary roles from displacing the core value.']],
      ['Prioritize with evidence', ['For every proposed capability, record the user need, expected outcome, evidence supporting it, effort, dependencies, and cost of being wrong. A simple now, next, later view is often easier to govern than a detailed scoring formula.', 'Prototype uncertain interactions and investigate high-risk integrations before committing to the complete build. A short technical spike or usability test can remove more uncertainty than several weeks of implementation.']],
      ['Keep quality inside the scope', ['Security, accessibility, performance, analytics, error handling, backups, and operational visibility are not optional polish. The appropriate depth varies, but omitting them can make early feedback misleading or expose the business to avoidable risk.', 'Define a release threshold covering supported devices, critical automated tests, privacy requirements, monitoring, recovery, customer support, and ownership of production incidents.']],
      ['Measure and decide', ['Select a small group of signals connected to the main assumption: activation, successful task completion, repeat use, time saved, qualified enquiries, conversion, or retention. Avoid treating downloads or page views as proof of value by themselves.', 'Before launch, agree what evidence would lead the team to continue, revise, narrow, or stop. An MVP creates value when it improves the next decision—not merely when it reaches production.']]
    ]
  },
  'preparing-for-cloud-migration': {
    title: 'Preparing for a Cloud Migration: A Practical Checklist',
    description: 'Plan a safer cloud migration by mapping dependencies, selecting migration paths, establishing controls, testing recovery, and moving workloads in stages.',
    published: '2026-09-23',
    readingTime: '9 min read',
    intro: 'A cloud migration succeeds when services remain understandable, recoverable, secure, and supportable after the move. Preparation should focus on dependencies and operating responsibility, not only infrastructure provisioning.',
    sections: [
      ['Build a dependable inventory', ['Document applications, databases, storage, scheduled jobs, domains, certificates, identity providers, external APIs, network dependencies, data flows, owners, and current support expectations. Include manual processes that may not appear in architecture diagrams.', 'Record traffic patterns, resource utilization, data growth, availability needs, recovery objectives, licensing constraints, and sensitive-data classifications. These facts shape the target design and migration order.']],
      ['Choose a migration path per workload', ['Rehosting, replatforming, refactoring, replacing, retaining, and retiring solve different problems. Do not force every workload into the same approach. A stable low-change service may move largely unchanged, while a fragile system might need staged modernization.', 'For each workload, document the proposed path, expected benefit, dependencies, rollback option, test approach, decision owner, and conditions that must be met before migration.']],
      ['Establish the landing zone first', ['Set up account or subscription structure, identity, least-privilege access, network boundaries, encryption, key management, logging, budgets, tagging, policy enforcement, and environment separation before moving production data.', 'Use version-controlled infrastructure and repeatable deployment pipelines where practical. Repeatability makes reviews, recovery, and later environments more reliable than manual configuration.']],
      ['Design observability and recovery', ['Define service indicators, dashboards, actionable alerts, log retention, audit trails, backup schedules, and escalation ownership. Monitoring added after migration often misses the signals teams need during the riskiest period.', 'Test restoration rather than assuming backups work. Confirm recovery time and recovery point expectations with business owners, and document what happens when a dependency or region becomes unavailable.']],
      ['Migrate in controlled waves', ['Begin with a representative but lower-risk workload, validate the process, and update the runbook before larger waves. Each wave should have readiness checks, a change window, communications, validation steps, rollback criteria, and an accountable decision maker.', 'After each move, compare reliability, performance, security posture, and cost with the baseline. Decommission old resources only after data retention, rollback, and stakeholder requirements are satisfied.']]
    ]
  }
};

export const articleSlugs = Object.keys(articles);
