export const articles = {
  'planning-a-web-development-brief': {
    title: 'How to Plan a Web Development Brief',
    description: 'A practical web development brief template covering business goals, audiences, content, integrations, constraints, measurement, and launch ownership.',
    published: '2026-09-23',
    readingTime: '7 min read',
    intro: 'A useful website brief does not prescribe every screen. It gives the project team enough context to make sound decisions, identify risk early, and agree on what success means.',
    sections: [
      ['Start with the business outcome', ['Explain why the project exists before listing pages or features. Useful outcomes include increasing qualified enquiries, reducing support requests, improving recruitment, enabling self-service, or replacing a system that is difficult to maintain.', 'Add a small set of measurable indicators. These might include completed enquiries, successful purchases, task-completion rate, organic landing-page traffic, publishing time, or support-ticket volume.']],
      ['Describe the audience and their decisions', ['Identify the primary audiences, what they already know, what questions they need answered, and what action they should be able to complete. Include important accessibility, language, device, and location considerations.', 'Real customer questions are more useful than vague personas. Sales calls, support messages, internal search terms, and analytics can reveal the language and concerns the website needs to address.']],
      ['Inventory content, functionality, and integrations', ['List existing content that can be retained, material that needs revision, and new content that must be created. Assign an owner and approval path because late content is a common cause of delayed launches.', 'Describe functional needs as user journeys: request a quote, find a service, purchase a product, book a time, or manage an account. Document integrations such as payments, CRM, email marketing, analytics, authentication, inventory, and internal APIs.']],
      ['Make constraints visible', ['State the target launch window, available budget range, legal or compliance requirements, hosting constraints, internal technologies, and people responsible for decisions. Constraints help the team recommend an appropriate scope instead of an idealized one.', 'Separate requirements that are essential for launch from useful later improvements. This protects the central outcome when new ideas appear during delivery.']],
      ['Define launch and ownership', ['A website needs an owner after release. Agree who will publish content, review analytics, manage software updates, monitor forms and uptime, respond to security issues, and prioritize improvements.', 'Ask prospective partners to explain discovery, accessibility, performance, technical SEO, testing, migration, analytics, deployment, training, documentation, and post-launch support. Their answers are more useful than a list of technologies alone.']]
    ]
  },
  'choosing-an-mvp-scope': {
    title: 'Choosing an MVP Scope That Produces Useful Evidence',
    description: 'Learn how to define an MVP around one valuable outcome, prioritize assumptions, control technical risk, and plan measurable product learning.',
    published: '2026-09-23',
    readingTime: '8 min read',
    intro: 'A minimum viable product is not the smallest collection of features a team can ship. It is the smallest dependable product that tests the most important assumption and delivers a recognizable outcome for a specific user.',
    sections: [
      ['Name the promise and the riskiest assumption', ['Write one sentence describing who the product helps, the problem it addresses, and the result it enables. If the sentence contains several audiences or outcomes, the first release may already be too broad.', 'Then list what must be true for the product to work: users experience the problem, the proposed workflow is acceptable, required data is available, integrations are feasible, and the operating model is sustainable. Test the assumption that could invalidate the project first.']],
      ['Map one complete journey', ['Choose the central journey from entry to completed outcome. Include necessary states such as validation, confirmation, failure, cancellation, permissions, and recovery—not only the happy path.', 'Supporting features belong in the MVP only when the central journey cannot be trusted or operated without them. This distinction prevents dashboards, preferences, and secondary roles from displacing the core value.']],
      ['Prioritize with evidence', ['For every proposed capability, record the user need, expected outcome, evidence supporting it, effort, dependencies, and cost of being wrong. A simple now, next, later view is often easier to govern than a detailed scoring formula.', 'Prototype uncertain interactions and investigate high-risk integrations before committing to the complete build. A short technical spike or usability test can remove more uncertainty than several weeks of implementation.']],
      ['Keep quality inside the scope', ['Security, accessibility, performance, analytics, error handling, backups, and operational visibility are not optional polish. The appropriate depth varies, but omitting them can make early feedback misleading or expose the business to avoidable risk.', 'Define a release threshold covering supported devices, critical automated tests, privacy requirements, monitoring, recovery, customer support, and ownership of production incidents.']],
      ['Measure and decide', ['Select a small group of signals connected to the main assumption: activation, successful task completion, repeat use, time saved, qualified enquiries, conversion, or retention. Avoid treating downloads or page views as proof of value by themselves.', 'Before launch, agree what evidence would lead the team to continue, revise, narrow, or stop. An MVP creates value when it improves the next decision—not merely when it reaches production.']]
    ]
  },
  'preparing-for-cloud-migration': {
    title: 'Preparing for a Cloud Migration: A Practical Checklist',
    description: 'Plan a safer cloud migration by mapping dependencies, selecting migration paths, establishing controls, testing recovery, and moving workloads in stages.',
    published: '2026-09-23',
    readingTime: '9 min read',
    intro: 'A cloud migration succeeds when services remain understandable, recoverable, secure, and supportable after the move. Preparation should focus on dependencies and operating responsibility, not only infrastructure provisioning.',
    sections: [
      ['Build a dependable inventory', ['Document applications, databases, storage, scheduled jobs, domains, certificates, identity providers, external APIs, network dependencies, data flows, owners, and current support expectations. Include manual processes that may not appear in architecture diagrams.', 'Record traffic patterns, resource utilization, data growth, availability needs, recovery objectives, licensing constraints, and sensitive-data classifications. These facts shape the target design and migration order.']],
      ['Choose a migration path per workload', ['Rehosting, replatforming, refactoring, replacing, retaining, and retiring solve different problems. Do not force every workload into the same approach. A stable low-change service may move largely unchanged, while a fragile system might need staged modernization.', 'For each workload, document the proposed path, expected benefit, dependencies, rollback option, test approach, decision owner, and conditions that must be met before migration.']],
      ['Establish the landing zone first', ['Set up account or subscription structure, identity, least-privilege access, network boundaries, encryption, key management, logging, budgets, tagging, policy enforcement, and environment separation before moving production data.', 'Use version-controlled infrastructure and repeatable deployment pipelines where practical. Repeatability makes reviews, recovery, and later environments more reliable than manual configuration.']],
      ['Design observability and recovery', ['Define service indicators, dashboards, actionable alerts, log retention, audit trails, backup schedules, and escalation ownership. Monitoring added after migration often misses the signals teams need during the riskiest period.', 'Test restoration rather than assuming backups work. Confirm recovery time and recovery point expectations with business owners, and document what happens when a dependency or region becomes unavailable.']],
      ['Migrate in controlled waves', ['Begin with a representative but lower-risk workload, validate the process, and update the runbook before larger waves. Each wave should have readiness checks, a change window, communications, validation steps, rollback criteria, and an accountable decision maker.', 'After each move, compare reliability, performance, security posture, and cost with the baseline. Decommission old resources only after data retention, rollback, and stakeholder requirements are satisfied.']]
    ]
  }
};

export const articleSlugs = Object.keys(articles);
