export const seoPages = {
  about: {
    label: 'About', title: 'About Nixoware | Web, App and Software Development Company',
    description: 'Learn how Nixoware combines strategy, UI/UX design, web development, mobile apps, custom software, and cloud engineering for growing businesses in India.',
    eyebrow: 'ABOUT NIXOWARE', heading: 'Technology built around real business progress.',
    intro: 'Nixoware is a web, mobile app, and custom software development company serving growing businesses and organizations across India. We bring product thinking, UI/UX design, engineering, and practical support together so every engagement has a clear purpose and a maintainable result.',
    cards: [['Who founded Nixoware', 'Nixoware was created to give growing organizations a practical technology partner for websites, apps, software, and ongoing digital improvement.'], ['Our expertise', 'Our work spans website development, mobile applications, UI/UX, custom web applications, e-commerce, cloud operations, technical SEO, and maintenance.'], ['How we work', 'We clarify goals, users, content, constraints, technology, ownership, and measures of success before recommending a focused delivery plan.'], ['Where we work', 'We support clients across India through clear communication, remote collaboration, and a delivery process designed around the people who will own the outcome.']],
    sections: [
      ['A practical development methodology', 'Discovery establishes the business outcome, audience, requirements, content, risks, and success measures. Design makes important decisions visible. Engineering builds and tests the solution. Launch and support keep the result useful after release.'],
      ['Technologies chosen for fit', 'We select frameworks, content platforms, APIs, integrations, analytics, and cloud services around the product, team skills, budget, performance needs, and future ownership rather than novelty alone.'],
      ['Industries and organizations', 'We support healthcare, education and events, professional services, product and testing organizations, startups, and established teams modernizing important customer or internal experiences.'],
      ['Why clients choose Nixoware', 'Clients need clear communication, thoughtful engineering, accessible experiences, realistic scope, and support after launch. We make decisions visible and document the systems we deliver so teams can operate them with confidence.']
    ],
    links: [['Explore our services', '/services'], ['View our portfolio', '/portfolio'], ['Discuss your project', '/contact']]
  },
  services: {
    label: 'Services', title: 'Software Development & IT Services in India',
    description: 'Explore Nixoware services for web development, mobile apps, custom software, ecommerce, UI/UX design, cloud solutions, and digital marketing.',
    eyebrow: 'SOFTWARE DEVELOPMENT & IT SERVICES', heading: 'We design, build and run digital technology.',
    intro: 'From business websites and mobile apps to custom software, cloud platforms, search growth and automated delivery pipelines—Nixoware brings strategy, design, engineering and operations together in one team.',
    cards: [
      ['Web development', 'Fast, accessible websites and web applications designed for users and search engines.', '/web-development'],
      ['Mobile app development', 'Useful, reliable mobile experiences for iOS, Android, and cross-platform delivery.', '/mobile-app-development'],
      ['Software development', 'Custom platforms, integrations, APIs, and internal systems shaped around your operations.', '/software-development'],
      ['Ecommerce development', 'Conversion-focused stores, product catalogues, checkout integrations, and ongoing optimization.', '/ecommerce-development'],
      ['UI/UX design', 'Research, information architecture, interaction design, prototypes, and design systems.', '/ui-ux-design'],
      ['Cloud solutions', 'Cloud migration, DevOps automation, observability, security, and cost management.', '/cloud-solutions'],
      ['SEO & SMO', 'Technical SEO, search-focused content, social media foundations, measurement, and iterative growth.', '/digital-marketing'],
      ['CI/CD pipelines', 'Automated build, test, approval, deployment, monitoring, and rollback workflows.', '/cloud-solutions']
    ],
    sections: [['One accountable delivery team', 'Strategy, design, engineering, and operations work from the same priorities. This reduces handoffs and keeps the experience, code, and infrastructure aligned.'], ['Built to evolve', 'We use modular architecture, version control, automated checks, and clear documentation so your digital systems can adapt as requirements change.']],
    links: [['Start a conversation', '/contact'], ['See selected work', '/portfolio']]
  },
  'web-development': {
    label: 'Web Development', title: 'Website Development Company | Business Web Development | Nixoware',
    description: 'Nixoware is a website development company providing business website development, custom web development, responsive websites, CMS development, and website redesign services.',
    eyebrow: 'WEB DEVELOPMENT', heading: 'Web Development Company in India',
    intro: 'Nixoware provides professional website development for growing businesses, organizations, and service teams across India. We plan, design, develop, test, launch, and maintain websites that communicate clearly, perform well, support search visibility, and give your team a dependable platform for growth.',
    cards: [['Business website development', 'Professional websites for growing businesses that explain your value, build trust, and turn visits into qualified enquiries.', '/contact'], ['Corporate website development', 'Clear information architecture, flexible content, and conversion paths for established organizations and service companies.', '/contact'], ['Custom website development', 'Purpose-built websites, portals, dashboards, and browser-based tools shaped around your operations and integrations.', '/software-development'], ['Responsive website development', 'Accessible layouts and reliable interactions designed for phones, tablets, desktops, and real-world network conditions.', '/ui-ux-design'], ['CMS development', 'Manageable publishing workflows with structured content, permissions, migration support, and documentation for your team.', '/contact'], ['Website redesign services', 'Improve an existing website with clearer journeys, stronger content, better performance, accessibility, and maintainable implementation.', '/contact'], ['SEO-friendly website development', 'Semantic structure, technical SEO foundations, performance, analytics, redirects, and content patterns that support organic discovery.', '/digital-marketing'], ['Website maintenance and support', 'Security updates, backups, monitoring, content changes, fixes, performance improvements, and continuing feature development.', '/services']],
    sections: [['Website development services', 'Our website development services cover discovery, information architecture, UX and UI design, frontend and backend implementation, CMS development, integrations, technical SEO, testing, deployment, analytics, and post-launch support. Scope follows the business outcome rather than a fixed page count.'], ['Business website development', 'A business website should help the right people understand what you do, trust your organization, and take the next step. We shape page structure, messaging, calls to action, enquiry routes, and content ownership around how your customers make decisions.'], ['Corporate website development', 'Corporate and professional service websites often need multiple audiences, departments, locations, services, resources, and approval owners. We create a clear content model that remains useful as the organization grows instead of becoming a collection of disconnected pages.'], ['Custom website development', 'When a standard brochure site cannot support the workflow, we build custom web applications, portals, dashboards, booking journeys, and API integrations. We define permissions, data, error states, and operational ownership before implementation.'], ['Responsive web design and CMS development', 'Responsive website development starts with content and tasks, then adapts layouts and interactions for different screens. A suitable CMS gives the right people control over publishing while protecting structure, quality, accessibility, and search-friendly content.'], ['Website redesign and SEO-friendly development', 'A redesign should solve a measurable problem, not simply change the visual style. We review analytics, search performance, content, accessibility, forms, speed, redirects, and user journeys before recommending a rebuild, staged improvement, or focused fix.'], ['Our website development process', 'Discovery defines audiences, requirements, content, integrations, budget, risks, and success measures. Design validates the experience. Development builds and tests the solution. Launch covers deployment, analytics, redirects, training, and handover. Support keeps the website secure, accurate, and useful after release.'], ['Technologies and platforms', 'We choose technology around your publishing workflow, integration needs, internal skills, budget, and expected scale. Projects can include Next.js and React, Node.js APIs, content management systems, payment and CRM integrations, analytics, cloud hosting, and maintainable responsive interfaces.']],
    faqs: [['What does a website development company do?', 'A website development company plans, designs, builds, tests, launches, and maintains websites or web applications around a business goal and its users.'], ['How much does business website development cost?', 'The cost depends on page count, content, design, CMS needs, integrations, custom functionality, SEO requirements, and ongoing support. Nixoware recommends a scope and estimate after reviewing those requirements.'], ['How long does it take to develop a website?', 'A focused business website can take less time than a multi-location corporate site or custom web application. Timeline depends on scope, content readiness, approvals, integrations, testing, and migration work.'], ['What is the difference between website redesign and new website development?', 'A redesign improves an existing platform when its content, structure, or implementation can be retained. New website development is more appropriate when the current technology, information architecture, or workflows cannot support the required outcome.'], ['Can you provide website maintenance after launch?', 'Yes. Support can include security updates, backups, uptime and form monitoring, content changes, performance work, technical SEO checks, and new features.']],
    links: [['Discuss a web project', '/contact'], ['View our portfolio', '/portfolio'], ['Explore UI/UX design', '/ui-ux-design'], ['Read website development insights', '/blog/planning-a-web-development-brief']]
  },
  'website-maintenance': {
    label: 'Website Maintenance', title: 'Website Maintenance Services | Security, Updates & Support | Nixoware',
    description: 'Nixoware provides website maintenance services for security updates, backups, uptime, website performance optimization, content changes, and ongoing support.',
    eyebrow: 'WEBSITE MAINTENANCE', heading: 'Website Maintenance Services for Growing Businesses',
    intro: 'A website needs ongoing care after launch. Nixoware provides website support services that keep your site secure, current, available, fast, and useful for customers. We can work alongside your team or take responsibility for a dependable maintenance routine.',
    cards: [['Basic website maintenance', 'Routine software updates, backups, uptime checks, broken-link checks, form testing, and a clear issue list for a healthy website.', '/contact'], ['Business website maintenance', 'Security monitoring, content changes, performance reviews, analytics checks, technical SEO checks, and priority fixes for active business websites.', '/contact'], ['Advanced website support', 'Ongoing improvements, integrations, feature work, incident response, recovery planning, and a roadmap for websites that support important operations.', '/contact'], ['Website security maintenance', 'Security updates, access reviews, certificate checks, dependency reviews, backup verification, and practical recovery preparation.', '/contact'], ['Website performance optimization', 'Page-speed reviews, image and script improvements, Core Web Vitals checks, uptime monitoring, and testing of important customer journeys.', '/contact'], ['Website updates and support', 'Content publishing, landing-page changes, bug fixes, design refinements, redirects, analytics, and technical guidance when your team needs it.', '/contact']],
    sections: [['What website maintenance includes', 'Website maintenance services can include security and software updates, backups, uptime and SSL checks, broken-link checks, form testing, content updates, analytics reviews, technical SEO checks, performance optimization, and documentation. The exact routine should reflect the risk and importance of your website.'], ['Basic, business, and advanced support', 'Basic website maintenance suits a smaller site that needs dependable checks and routine updates. Business website maintenance adds active monitoring, content and performance work, and priority response. Advanced website support adds ongoing development, integrations, recovery planning, and a prioritized improvement roadmap.'], ['Website security maintenance', 'Keep accounts controlled, dependencies current, certificates valid, backups restorable, and changes reviewable. We look for avoidable exposure and make ownership clear so security does not depend on one person remembering an occasional task.'], ['Website performance optimization', 'A fast website helps customers complete important tasks and gives search engines a better technical foundation. We review loading behavior, images, scripts, layouts, forms, uptime, and mobile journeys before recommending focused improvements.'], ['Website maintenance versus redesign', 'Maintenance is appropriate when the platform can still support the business and the main need is reliable care or targeted improvement. A redesign may be better when information architecture, technology, accessibility, user journeys, or ownership problems are fundamental.'], ['How often should a website be updated?', 'Critical security updates, backups, uptime, and forms need regular attention. A monthly review is a useful baseline for content, performance, indexing, redirects, analytics, and customer journeys, while urgent issues should be handled as they appear.'], ['Our maintenance process', 'We begin by reviewing the website, access, dependencies, backups, performance, forms, content ownership, and risks. We then agree a support scope, priorities, communication path, and review rhythm so maintenance produces visible value rather than a vague promise of availability.']],
    faqs: [['What are website maintenance services?', 'Website maintenance services keep a website secure, current, available, accurate, and useful through updates, backups, monitoring, content changes, performance work, form checks, and technical support.'], ['How much does website maintenance cost?', 'Cost depends on website size, technology, update frequency, security risk, integrations, response expectations, content volume, and ongoing development needs. Nixoware can recommend a basic, business, or advanced support scope after reviewing the site.'], ['Do you provide WordPress maintenance?', 'Nixoware can review the website platform and recommend an appropriate maintenance approach. The support scope should be based on the actual platform, dependencies, security needs, and publishing workflow rather than assuming every site needs the same package.'], ['How often should a website be maintained?', 'Review critical security, backups, uptime, and forms regularly. A monthly maintenance review is a useful baseline for content, performance, indexing, redirects, and analytics, with urgent security issues handled sooner.'], ['Can website maintenance include new features?', 'Yes. Advanced website support can include new pages, integrations, design improvements, workflow changes, and prioritized feature development alongside routine maintenance.']],
    links: [['Discuss website support', '/contact'], ['Explore website development', '/web-development'], ['Read the maintenance checklist', '/blog/website-maintenance-checklist-for-small-businesses'], ['View our portfolio', '/portfolio']]
  },
  'mobile-app-development': {
    label: 'Mobile Apps', title: 'Mobile App Development Company | Android & iOS App Development',
    description: 'Nixoware is a mobile app development company providing Android app development, iOS app development, cross-platform apps, custom mobile software, APIs, testing, launch, and maintenance.',
    eyebrow: 'MOBILE APP DEVELOPMENT', heading: 'Mobile App Development Company in India',
    intro: 'Nixoware is a mobile app development company helping businesses turn product ideas into focused, usable applications for Android and iOS. We connect product discovery, mobile UI/UX, application engineering, API and backend development, testing, store launch, analytics, and ongoing maintenance.',
    cards: [['Android app development', 'Reliable Android applications planned around device coverage, user journeys, business goals, and long-term support.', '/contact'], ['iOS app development', 'Focused iPhone and iPad experiences with thoughtful interaction design, secure integrations, testing, and release preparation.', '/contact'], ['Cross-platform app development', 'A shared application approach when it supports the required experience, delivery timeline, budget, and maintenance model.', '/contact'], ['UI/UX for mobile apps', 'Research, flows, wireframes, prototypes, visual design, accessibility, and interaction patterns built for mobile contexts.', '/ui-ux-design'], ['API and backend development', 'Secure APIs, authentication, payments, notifications, analytics, databases, and connections to existing business systems.', '/software-development'], ['Mobile app testing', 'Functional, device, network, usability, performance, security, and release testing before customers depend on the app.', '/contact'], ['App store launch', 'Store assets, release preparation, privacy details, staged rollout, monitoring, crash reporting, and post-launch iteration.', '/contact'], ['App maintenance', 'Compatibility updates, security fixes, performance improvements, feature releases, analytics reviews, and operational support.', '/services']],
    sections: [['Android app development', 'We plan Android apps around the users, devices, permissions, integrations, and support expectations that matter to your product. Testing considers different screen sizes, operating system versions, connectivity conditions, and real-world workflows.'], ['iOS app development', 'iOS development combines clear interaction design with dependable application behavior, privacy considerations, backend integration, device testing, and a release process your team can operate after launch.'], ['Cross-platform app development', 'Cross-platform development can reduce duplicated implementation when the product needs a consistent experience across Android and iOS. We recommend it only when the shared approach fits the product interactions, performance needs, integrations, and future roadmap.'], ['UI/UX for mobile apps', 'Good mobile UX reduces friction in the moments that matter: onboarding, search, forms, payments, notifications, and recovery from errors. We validate the core journeys before committing the full build.'], ['API and backend development', 'Mobile applications need dependable services for identity, data, payments, notifications, files, analytics, and business rules. We design documented APIs and clear failure states so the app and the teams supporting it know what happens next.'], ['App testing and store launch', 'Quality work covers functional journeys, device compatibility, performance, accessibility, privacy, network changes, and release readiness. Launch preparation includes store content, versioning, monitoring, and a plan for responding to early feedback.'], ['App maintenance and upgrades', 'A mobile app needs care after release as operating systems, devices, dependencies, security expectations, and user needs change. Support can include fixes, upgrades, analytics reviews, feature work, and release management.'], ['Mobile app development cost', 'Mobile app cost depends on the number of platforms, user roles, screens, integrations, backend complexity, offline behavior, security requirements, testing depth, and post-launch support. A focused first release is usually easier to estimate than a complete product roadmap.'], ['Our mobile app development process', 'Discovery defines the audience, product promise, essential journey, constraints, and success measures. Design makes the experience testable. Engineering builds the app and backend. Testing and release preparation protect quality, while post-launch analytics guide the next improvements.']],
    faqs: [['How much does mobile app development cost?', 'Cost depends on whether the app targets Android, iOS, or both; the number of journeys and roles; backend and API work; payments; notifications; security; testing; and ongoing support. Nixoware estimates after defining a practical first release.'], ['Should I build a native or cross-platform mobile app?', 'Native development can be appropriate for platform-specific experiences or demanding device capabilities. Cross-platform development can be effective when Android and iOS share most journeys and the product benefits from a common implementation. The right choice depends on the product, users, budget, and roadmap.'], ['How long does it take to build a mobile app?', 'Timeline varies with product scope, design readiness, integrations, backend work, testing, and store requirements. Defining a focused first release gives the team a more dependable schedule than estimating an entire product from a feature list.'], ['Can you develop the backend and API for a mobile app?', 'Yes. Backend work can include authentication, databases, APIs, payments, notifications, file handling, analytics, permissions, integrations, and monitoring.'], ['Do you provide mobile app maintenance after launch?', 'Yes. Maintenance can include operating system compatibility, security updates, bug fixes, performance work, analytics reviews, feature upgrades, and store release support.']],
    links: [['Plan your mobile app', '/contact'], ['Explore UI/UX design', '/ui-ux-design'], ['Explore custom software', '/software-development'], ['View our portfolio', '/portfolio'], ['Read product insights', '/blog/choosing-an-mvp-scope']]
  },
  'software-development': {
    label: 'Software Development', title: 'Custom Web Application Development Company | Nixoware',
    description: 'Nixoware develops custom web applications, business software, portals, dashboards, APIs, integrations, and workflow automation for growing organizations.',
    eyebrow: 'CUSTOM SOFTWARE DEVELOPMENT', heading: 'Custom Software Development Company in India',
    intro: 'When off-the-shelf tools create friction, Nixoware builds custom web applications and business software that connect workflows, data, customers, and teams. We design maintainable systems with clear ownership, secure access, useful automation, and a roadmap for change.',
    cards: [['CRM systems', 'Customer records, sales workflows, follow-up, permissions, reporting, and integrations shaped around your process.', '/contact'], ['Customer portals', 'Secure self-service areas for documents, requests, bookings, account information, status updates, and communication.', '/contact'], ['Employee portals', 'Internal tools for teams, approvals, resources, task visibility, and role-based access to business information.', '/contact'], ['Booking systems', 'Availability, schedules, requests, confirmations, reminders, payments, and operational workflows in one experience.', '/contact'], ['Admin dashboards', 'Decision-ready views for operations, sales, support, inventory, performance, and exceptions that need action.', '/contact'], ['Inventory systems', 'Product, stock, order, supplier, warehouse, and fulfilment data connected to the workflows that use it.', '/contact'], ['Business automation', 'Reduce repetitive work with rules, notifications, approvals, scheduled jobs, and integrations between existing systems.', '/contact'], ['API integrations', 'Documented APIs and reliable connections for CRM, ERP, payments, identity, analytics, and partner platforms.', '/contact']],
    sections: [['Custom web application development', 'A custom web application is useful when a business-critical workflow cannot be handled reliably by disconnected spreadsheets or generic tools. We map the current process, define roles and data, and build the smallest dependable system that improves the outcome.'], ['Business portals and dashboards', 'Portals and dashboards should help people take action, not only display information. We connect useful views with permissions, statuses, assignments, notes, approvals, and links to the underlying records.'], ['Workflow automation and integrations', 'Automation can reduce repeated entry, missed handoffs, and slow approvals. We design clear rules and failure handling, then connect APIs, payments, identity, CRM, ERP, analytics, and other services where they improve the workflow.'], ['Secure, maintainable architecture', 'We consider authentication, roles, data boundaries, audit history, backups, monitoring, deployments, documentation, and ownership from the beginning. This keeps custom software easier to support as the organization changes.'], ['Custom software development cost', 'Cost depends on the number of user roles, workflows, screens, integrations, data complexity, security needs, reporting, automation, testing, and ongoing support. A focused first release gives better evidence and a more dependable estimate than a broad feature list.'], ['Our software development process', 'Discovery maps the current operation and desired outcome. Design makes the workflow testable. Engineering builds the application and integrations. Testing, security checks, deployment, monitoring, and documentation prepare the system for real ownership after launch.']],
    faqs: [['When does a business need custom software?', 'Custom software is worth considering when manual work, disconnected systems, limited permissions, repeated errors, or generic tools prevent an important business process from working well.'], ['What types of custom web applications do you build?', 'We build CRM systems, customer and employee portals, booking systems, admin dashboards, inventory tools, workflow automation, API integrations, and other browser-based business applications.'], ['How much does custom software development cost?', 'Cost depends on workflows, roles, data, integrations, security, reporting, automation, testing, and support. Nixoware recommends a phased scope so the first release can prove value before broader investment.'], ['Can custom software integrate with existing systems?', 'Yes. We can plan and develop connections to CRM, ERP, payment, identity, analytics, inventory, cloud, and partner systems through documented APIs or other appropriate integration methods.'], ['Can you maintain custom software after launch?', 'Yes. Support can include monitoring, security updates, bug fixes, infrastructure work, documentation, user feedback, and a prioritized roadmap for new capabilities.']],
    links: [['Discuss custom software', '/contact'], ['Explore website development', '/web-development'], ['Explore cloud solutions', '/cloud-solutions'], ['Read about custom dashboards', '/blog/when-a-custom-business-dashboard-is-worth-building'], ['View our portfolio', '/portfolio']]
  },
  'ecommerce-development': {
    label: 'Ecommerce', title: 'E-commerce Development Company | Online Store Development | Nixoware',
    description: 'Nixoware provides e-commerce website development, online store development, custom e-commerce design, payment gateway integration, and ongoing support.',
    eyebrow: 'ECOMMERCE DEVELOPMENT', heading: 'Ecommerce Development Company in India',
    intro: 'Nixoware builds online stores that balance customer experience with dependable operations. E-commerce website development can include product discovery, merchandising, checkout, payment gateway integration, fulfilment, analytics, performance, organic search, and ongoing support as one connected system.',
    cards: [['E-commerce website development', 'Responsive storefronts with product discovery, categories, search, filtering, cart, checkout, customer accounts, and order status.', '/contact'], ['Online store development', 'A commerce foundation shaped around catalogue complexity, content needs, team workflow, integrations, and expected growth.', '/contact'], ['Custom e-commerce development', 'Purpose-built shopping, product, pricing, account, marketplace, and operational workflows for businesses with specific needs.', '/contact'], ['E-commerce website design', 'Clear product information, mobile-first shopping journeys, accessible interfaces, trust signals, and conversion-focused interaction design.', '/ui-ux-design'], ['Payment gateway integration', 'Secure payment journeys with success, failure, refund, cancellation, webhook, and reconciliation states considered.', '/software-development'], ['Commerce integrations', 'Inventory, shipping, tax, CRM, ERP, marketplace, email, analytics, and fulfilment connections that reduce manual work.', '/software-development'], ['E-commerce SEO and performance', 'Crawlable categories, product data, structured markup, canonical controls, internal linking, speed, and measurable search foundations.', '/digital-marketing'], ['E-commerce maintenance', 'Product updates, security, payment checks, backups, monitoring, content changes, analytics reviews, and continuing improvements.', '/website-maintenance']],
    sections: [['E-commerce development services', 'Our e-commerce development services cover discovery, information architecture, storefront design, catalogue structure, product data, checkout, payments, integrations, analytics, technical SEO, testing, deployment, and ongoing support.'], ['Choose the right online store foundation', 'The platform should reflect product variants, catalogue size, content needs, tax and delivery rules, integrations, team workflow, and expected transaction volume. We assess these requirements before recommending an implementation.'], ['Protect the checkout and payment journey', 'We test carts, discounts, stock states, addresses, delivery rules, payment success and failure, refunds, duplicate actions, delayed confirmations, and order records. Clear recovery paths protect both revenue and customer trust.'], ['Connect products, orders, and fulfilment', 'An online store must connect what customers see with what the business can fulfil. Inventory, shipping, tax, CRM, ERP, marketplace, email, and warehouse connections need clear ownership and failure handling.'], ['E-commerce SEO and website performance', 'Search-friendly category and product structure, useful product content, structured data, internal linking, redirects, mobile usability, and fast loading support both discovery and conversion.'], ['E-commerce website maintenance', 'After launch, stores need product and content updates, payment checks, security work, backups, performance reviews, analytics, order-flow testing, and support for new operational requirements.'], ['E-commerce development cost', 'Cost depends on catalogue complexity, product variants, design, accounts, checkout, payments, tax, delivery, inventory, integrations, migration, custom workflows, SEO, testing, and support. A focused first release gives a more dependable estimate.'], ['Our e-commerce development process', 'Discovery maps products, customers, operations, integrations, and success measures. Design validates shopping and checkout journeys. Engineering connects the storefront to commerce systems. Testing covers devices, payment states, fulfilment, analytics, and recovery before launch.']],
    faqs: [['How much does e-commerce website development cost?', 'Cost depends on products, variants, design, customer accounts, checkout, payment gateway integration, inventory, delivery, tax, third-party systems, migration, testing, and support. Nixoware recommends a scope after reviewing those requirements.'], ['What is included in online store development?', 'Online store development can include catalogue and product pages, search, filters, cart, checkout, payments, customer accounts, order management, shipping, inventory, analytics, technical SEO, and ongoing maintenance.'], ['Can you integrate a payment gateway?', 'Yes. Payment work should cover secure checkout, successful and failed payments, cancellations, refunds, delayed confirmations, webhook handling, order status, and reconciliation.'], ['Should I choose a hosted platform or custom e-commerce development?', 'The right choice depends on catalogue and workflow complexity, integrations, team skills, budget, control, and expected growth. A hosted platform can suit standard needs, while custom development is useful when important workflows need deeper control.'], ['Do you provide e-commerce website maintenance?', 'Yes. Support can include product and content changes, security, backups, payment and order-flow checks, performance, analytics, integrations, and new features.']],
    links: [['Plan an e-commerce project', '/contact'], ['Explore UI/UX design', '/ui-ux-design'], ['Explore website maintenance', '/website-maintenance'], ['Read the order flow checklist', '/blog/ecommerce-order-flow-checklist-for-growing-retailers'], ['View our portfolio', '/portfolio']]
  },
  'ui-ux-design': {
    label: 'UI/UX Design', title: 'UI/UX Design Services | Website & App UX Design | Nixoware',
    description: 'Nixoware provides UI/UX design services, website UX design, mobile app UI/UX design, product design, UX research, prototypes, and design systems.',
    eyebrow: 'UI/UX DESIGN', heading: 'Digital experiences made clear, useful, and consistent.',
    intro: 'Nixoware provides UI/UX design services for websites, mobile apps, and custom digital products. We connect UX research, business goals, interaction design, visual systems, prototyping, accessibility, and engineering reality so teams can make better product decisions before and during development.',
    cards: [['UX research', 'Understand users, stakeholders, tasks, constraints, and opportunities before choosing a solution.', '/contact'], ['Website UX design', 'Improve information architecture, navigation, content hierarchy, conversion paths, and responsive website journeys.', '/web-development'], ['Mobile app UI/UX design', 'Design onboarding, navigation, forms, notifications, permissions, and core mobile interactions for real contexts.', '/mobile-app-development'], ['Product design services', 'Connect product strategy, user flows, prototypes, interface design, and a prioritized roadmap for useful digital products.', '/contact'], ['Wireframes and prototypes', 'Make structure, interactions, edge cases, and risky assumptions visible before implementation.', '/contact'], ['Design systems', 'Create reusable components, tokens, states, accessibility rules, and documentation for consistent delivery.', '/contact']],
    sections: [['Problem: unclear user journeys', 'When people cannot find information, complete a task, or understand what happens next, the problem is often structural rather than cosmetic. We map the journey and make the highest-friction decisions visible.'], ['Research: evidence before assumptions', 'We combine stakeholder context, existing analytics, customer questions, support signals, and appropriate user research to understand what people need and where the current experience fails.'], ['Design: from flows to interface', 'We move from information architecture and task flows to wireframes, prototypes, visual direction, responsive layouts, and interaction states. The work accounts for loading, errors, empty states, permissions, and recovery.'], ['Result: a clearer, buildable experience', 'A useful design gives users a more understandable path and gives developers a more dependable specification. We document reusable patterns, accessibility needs, content behavior, and decisions that matter during implementation.'], ['Accessibility and responsive design', 'Readable hierarchy, keyboard interaction, contrast, focus states, labels, touch targets, responsive behavior, and assistive technology considerations are included from the start.'], ['Design handover and collaboration', 'We work with engineering and stakeholders through prototypes, reviews, design systems, specifications, and implementation feedback so the final product reflects the intended experience.']],
    faqs: [['What do UI/UX design services include?', 'UI/UX design services can include UX research, information architecture, user flows, wireframes, prototypes, visual interface design, responsive layouts, accessibility, design systems, usability testing, and developer handover.'], ['What is the difference between UI and UX design?', 'UX design focuses on structure, tasks, decisions, and the overall experience. UI design focuses on the visual interface, components, states, hierarchy, and interaction details. Strong product design connects both.'], ['Can you design a website or mobile app before development?', 'Yes. Prototypes and design systems can make important journeys testable before development, reduce uncertainty, and give engineering a clearer foundation.'], ['How does UX research improve a website or app?', 'Research helps teams understand user needs, language, obstacles, and priorities so design decisions respond to evidence instead of internal assumptions.']],
    links: [['Discuss your product design', '/contact'], ['Explore web development', '/web-development'], ['Explore mobile app development', '/mobile-app-development'], ['View our portfolio', '/portfolio']]
  },
  'cloud-solutions': {
    label: 'Cloud Solutions', title: 'Cloud Solutions and DevOps Company in India',
    description: 'Improve cloud migration, infrastructure, CI/CD, observability, reliability, security, and cost control with Nixoware.',
    eyebrow: 'CLOUD SOLUTIONS', heading: 'A dependable cloud foundation for products that need to grow.',
    intro: 'Nixoware helps teams plan migrations, automate delivery, improve visibility, and operate cloud infrastructure with clearer controls. The goal is not simply to move workloads, but to make systems easier to release and support.',
    cards: [['Cloud assessment', 'Application dependencies, risks, target architecture, migration waves, and recovery planning.'], ['DevOps automation', 'Version-controlled CI/CD pipelines, infrastructure as code, and repeatable environments.'], ['Reliability', 'Logs, metrics, alerts, backups, runbooks, service objectives, and incident readiness.'], ['Governance and cost', 'Access controls, ownership, budgets, resource reviews, and practical optimization.']],
    sections: [['Migrate in controlled stages', 'We prioritize workloads, establish landing-zone controls, test dependencies, and validate recovery before each migration stage. This gives stakeholders evidence at each decision point.'], ['Operate what you build', 'Architecture decisions include observability, support ownership, security maintenance, capacity, and cost from the beginning.']],
    links: [['Discuss your cloud roadmap', '/contact'], ['Explore software development', '/software-development']]
  },
  'digital-marketing': {
    label: 'Digital Marketing', title: 'Digital Marketing Company in India',
    description: 'Connect technical SEO, content, landing pages, analytics, and campaign optimization with Nixoware digital marketing services.',
    eyebrow: 'DIGITAL MARKETING', heading: 'Marketing systems built for measurable, sustainable growth.',
    intro: 'We connect content, search readiness, campaign experiences, and analytics so marketing activity has a reliable digital foundation. Work is tied to relevant audiences and meaningful business outcomes rather than surface-level traffic alone.',
    cards: [['Technical SEO', 'Crawlability, indexation, metadata, internal linking, structured content, and performance.'], ['Content foundations', 'Search intent, topic planning, service pages, editorial structure, and conversion paths.'], ['Campaign experiences', 'Focused landing pages, forms, tracking, and iterative experience improvement.'], ['Measurement', 'Analytics configuration, events, reporting, attribution context, and actionable reviews.']],
    sections: [['Earn relevance before links', 'Useful pages need a clear purpose, distinctive information, and a strong internal structure. Promotion works better once users and crawlers can understand the site.'], ['Measure outcomes, not noise', 'We define conversions and supporting signals before campaigns begin, then review performance in context rather than optimizing isolated metrics.']],
    links: [['Discuss your growth goals', '/contact'], ['Explore web development', '/web-development']]
  },
  contact: {
    label: 'Contact', title: 'Build Your Website, App or Custom Software | Contact Nixoware',
    description: 'Contact Nixoware to discuss website development, mobile apps, e-commerce, custom software, UI/UX design, maintenance, or cloud solutions in India.',
    eyebrow: 'CONTACT NIXOWARE', heading: 'Let us build your website, app, or custom software.',
    intro: 'Tell us what you want to build, improve, or maintain. Share your goals, current challenges, expected timeline, budget range if known, and any systems involved. We will help you identify a sensible next step and the right Nixoware capability.',
    cards: [['Phone', '+91 96504 29575. Call to discuss a project or request a first conversation.'], ['Email', 'nixoware@gmail.com. Send your goals, requirements, links, or project documents.'], ['Service area', 'Nixoware works with businesses and organizations across India through remote collaboration and clear delivery communication.'], ['Response', 'We review enquiries and respond with the next sensible step, questions, and a practical path forward.']],
    sections: [['What to include in your enquiry', 'Useful details include the business goal, audience, current website or product, required services, important integrations, timeline, decision makers, and the problem you want to solve. You do not need a complete specification before contacting us.'], ['Services we discuss', 'We can help with website development, mobile apps, e-commerce, custom web applications, UI/UX design, website maintenance, cloud solutions, technical SEO, and ongoing improvements.'], ['What happens next', 'We review your enquiry, arrange an initial conversation, clarify goals, scope, stakeholders, constraints, and decision points, then recommend a sensible next step.']],
    faqs: [['What services does Nixoware provide?', 'Nixoware provides website development, mobile app development, e-commerce, custom web applications, UI/UX design, website maintenance, cloud solutions, and technical SEO support.'], ['How quickly will Nixoware respond?', 'We review new enquiries and respond with clarifying questions or a suitable next step. The expected response timing can depend on the detail and complexity of the request.'], ['Can I contact Nixoware about an existing website or app?', 'Yes. We can discuss redesign, maintenance, performance, security, accessibility, integrations, content, new features, or a broader rebuild based on the current situation.']],
    links: [['Email Nixoware', 'mailto:nixoware@gmail.com'], ['Call +91 96504 29575', 'tel:+919650429575'], ['Explore our services', '/services']]
  },
  portfolio: {
    label: 'Portfolio', title: 'Web and Software Development Portfolio',
    description: 'View selected Nixoware website and digital experience work for education, events, technology, and product quality organizations.',
    eyebrow: 'SELECTED WORK', heading: 'Digital work shaped around each organization’s purpose.',
    intro: 'Our portfolio reflects focused collaboration across strategy, content, experience design, engineering, and launch. These selected projects demonstrate how we turn distinct organizational needs into clear digital experiences.',
    cards: [['Pune Education Forum', 'A responsive event and leadership platform presenting speakers, sessions, partners, and the forum’s vision.', '/portfolio/pune-education-forum-website'], ['Teknolab', 'A service-led website communicating independent testing capabilities across electronics, IT, lighting, and electrical products.', '/portfolio/teknolab-website']],
    sections: [['What our work includes', 'Engagements can span discovery, information architecture, interface design, frontend and backend development, technical SEO, deployment, analytics, and continuing improvements.'], ['Every case is different', 'We do not force projects into a fixed template. Scope and technology follow the audience, content, operational workflow, and outcomes that matter to the client.']],
    links: [['Discuss your project', '/contact'], ['Read our case studies', '/case-studies']]
  },
  'case-studies': {
    label: 'Case Studies', title: 'Digital Project Case Studies',
    description: 'Explore how Nixoware approaches website, software, product design, automation, DevOps, and cloud challenges.',
    eyebrow: 'CASE STUDIES', heading: 'The thinking behind dependable digital outcomes.',
    intro: 'Our case studies explain the context, decisions, delivery approach, and outcomes behind selected work. Client-approved detailed studies will be published here as engagements reach the appropriate stage.',
    cards: [['Education and events', 'Structuring a content-rich forum experience around speakers, agenda discovery, partners, and mobile visitors.'], ['Testing and compliance', 'Making complex laboratory capabilities understandable and easy to navigate for prospective customers.'], ['Cloud-enabled delivery', 'Connecting product development, automated releases, monitoring, and operational ownership.']],
    sections: [['Evidence over vague claims', 'A useful case study should explain the starting point, constraints, alternatives, work completed, and measurable result. We will publish figures only where they are accurate and approved.'], ['Looking for relevant experience?', 'Tell us about your industry and technical challenge. We can discuss applicable patterns and delivery experience without exposing confidential client information.']],
    links: [['View our portfolio', '/portfolio'], ['Contact our team', '/contact']]
  },
  blog: {
    label: 'Insights', title: 'Practical Web, Software and Cloud Guides',
    description: 'Actionable guides from Nixoware about website development, website maintenance, e-commerce, custom software, UX, cloud operations, and technical SEO for growing businesses.',
    eyebrow: 'NIXOWARE INSIGHTS', heading: 'Practical thinking for teams building digital products.',
    intro: 'Find practical guidance for planning, building, improving, and maintaining websites, online stores, mobile apps, and internal software. Each guide turns a real business question into useful checks, decisions, and next steps.',
    cards: [['Choosing a development company in India', 'Compare web, mobile app, custom software, Next.js, UI/UX, e-commerce, cost, and ongoing support capabilities.', '/blog/choosing-a-development-company-in-india'], ['Website development cost in India', 'What affects a website quote, including scope, content, design, integrations, SEO, testing, and support.', '/blog/website-development-cost-in-india'], ['SEO-friendly website development', 'How structure, performance, accessibility, internal links, and technical controls support search visibility.', '/blog/seo-friendly-website-development-guide'], ['Mobile app development cost', 'How platforms, features, backend APIs, design, testing, launch, and maintenance affect app budgets.', '/blog/mobile-app-development-cost-guide'], ['E-commerce website cost', 'Understand online store costs across products, checkout, payments, fulfilment, integrations, SEO, and support.', '/blog/ecommerce-website-development-cost-guide'], ['Custom software vs off-the-shelf', 'A practical way to compare workflow fit, integrations, ownership, recurring cost, and business value.', '/blog/custom-software-vs-off-the-shelf-software'], ['Website development brief template', 'Define website project requirements, content, integrations, budget, SEO, accessibility, testing, and launch ownership before development.', '/blog/planning-a-web-development-brief'], ['Choosing an MVP scope', 'How to separate the core product promise from features that can wait for evidence.', '/blog/choosing-an-mvp-scope'], ['Preparing for cloud migration', 'A practical view of dependencies, controls, observability, recovery, and phased validation.', '/blog/preparing-for-cloud-migration'], ['Hospital website creation', 'The patient trust, accessibility, privacy, mobile, local search, and workflow challenges hospitals must solve.', '/blog/hospital-website-creation-problems-and-success-steps'], ['Website maintenance for small businesses', 'A practical routine for security, backups, forms, performance, content, analytics, and ownership.', '/blog/website-maintenance-checklist-for-small-businesses'], ['Why contact forms lose leads', 'The common form, notification, mobile, and follow-up problems that quietly cost businesses enquiries.', '/blog/why-business-website-contact-forms-lose-leads'], ['E-commerce order flow checklist', 'How growing retailers can test product data, checkout, payments, fulfilment, and customer updates.', '/blog/ecommerce-order-flow-checklist-for-growing-retailers'], ['When to build a custom dashboard', 'A decision guide for turning repeated operational questions into a useful, maintainable business tool.', '/blog/when-a-custom-business-dashboard-is-worth-building']],
    sections: [['Five connected topic clusters', 'Explore website development, SEO-friendly websites, mobile apps, e-commerce, and custom software through cost guides, checklists, process explainers, practical questions, and industry-specific examples.'], ['From information to action', 'Each guide should help a reader understand a problem, choose a sensible next step, explore the relevant Nixoware service, review project evidence, and start a conversation when the timing is right.']],
    links: [['Explore our services', '/services'], ['Suggest a topic', '/contact']]
  }
};

export const seoSlugs = Object.keys(seoPages);
